let menuList = [
    {
      Id:1,
      title: "Front Desk",
      icon: "./assets/arrowGreyStroke.svg",
      img: "./assets/homeGreyStroke.svg",
      children: [
        { children: [], title: "Dashboard", icon: "", img: "",route:'/dashboard' },
        {
          children: [
            {
              children: [],
              title: "User Role",
              icon: "",
              active:'userRole',
              img: "",
              route: "/userRole",
            },
            {
              children: [],
              title: "User List",
              icon: "",
              active:'userList',
              img: "",
              route: "/userList",
            },
            {
              children: [],
              title: "Role and Permission",
              icon: "",
              img: "",
              icon: "",
              active:'roleandpermission',
              img: "",
              route:'/roleandpermission'
            },
          ],
          title: "User",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            { children: [], title: "Book Room", icon: "", img: "" ,route:'/bookingRoom'},
            { children: [], title: "Book Dorm", icon: "", img: "",route:'/bookingDorm' },
            { children: [], title: "Book List", icon: "", img: "",route:'/bookinglist' },
          ],
          title: "Booking",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            {
              children: [],
              title: "Coupon List",
              icon: "",
              active:'couponlist',
              img: "",
              route: "/couponlist",
            },
          ],
          title: "Coupon",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            { children: [], title: "Room Creation", icon: "", img: "" ,route:'/roomcreation'},
            {
              children: [],
              title: "Amenities List",
              icon: "",
              active:'amenities',
              img: "",
              route: "/amenities",
            },
            {
              children: [],
              title: "Category Type",
              icon: "",
              active:'catType',
              img: "",
              // route: "/catType",
            },
            {
              children: [],
              title: "Category List",
              icon: "",
              active:'catList',
              img: "",
              route: "/catList",
            },
            {
              children: [],
              title: "Sub Category List",
              icon: "",
              active:'subcategorylist',
              img: "",
              route: "/subcategorylist",
            },
            {
              children: [],
              title: "All Room Rate Plan",
              icon: "",
              active:'rateplan',
              img: "",
              route: "/rateplan",
            },
          ],
          title: "Inventory",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            { children: [], title: "Billing Details", icon: "", img: "",route:'/billingdetail' },
            {
              children: [],
              title: "Guest Folio",
              icon: "",
              img: "",
              route: "/guestFolio",
            },
            {
              children: [],
              title: "All Transaction",
              icon: "",
              img: "",
              route: "/allTransaction",
            },
            {
              children: [],
              title: "Expenses",
              icon: "",
              img: "",
              route: "/expenses",
            },
            {
              children: [],
              title: "Miscellaneous Income",
              icon: "",
              img: "",
              route: "/miscellaneousIncome",
            },
            {
              children: [],
              title: "Vendor Master",
              icon: "",
              img: "",
              route: "/vendorMaster",
            },
            {
              children: [],
              title: "Expense Category Master",
              icon: "",
              img: "",
              route: "/expenseCategoryMaster",
            },
          ],
          title: "Finance",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            {
              children: [],
              title: "View Hotels",
              icon: "",
              img: "",
              route: "/viewHotels",
            },
          ],
          title: "Hotel Master",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            {
              children: [],
              title: "All Tasks",
              icon: "",
              img: "",
              route: "/alltasks",
            },
          ],
          title: "Task Master",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            {
              children: [],
              title: "Nature of Visit",
              icon: "",
              img: "",
              route: "/natureOfVisit",
            },
            {
              children: [],
              title: "Profit Center",
              icon: "",
              img: "",
              route: "/profitCenter",
            },
            { children: [], title: "Area Code", icon: "", img: "",route:'/areacode' },
            { children: [], title: "Cash Drawer Settings", icon: "", img: "" },
            { children: [], title: "Cash Drawer", icon: "", img: "" },
            {
              children: [],
              title: "Facility Master",
              icon: "",
              img: "",
              route: "/facilityMaster",
            },
            {
              children: [],
              title: "Behavior Master",
              icon: "",
              img: "",
              route: "/behaviourMaster",
            },
            { children: [], title: "Company Master", icon: "", img: "" , route:'/companymaster' },
            { children: [], title: "Broker/OTA Master", icon: "", img: "",route:'/brokermaster' },
            { children: [], title: "System Settings", icon: "", img: "",route:'/systemsetting' },
            { children: [], title: "POS Settings", icon: "", img: "",route:'/possetting' },
            {
              children: [],
              title: "Currency Settings",
              icon: "",
              img: "",
              route: "/currencySettings",
            },
            { children: [], title: "Invoice Settings", icon: "", img: "", route: '/invoicesetting' },
            { children: [], title: "Auto Generate Invoice", icon: "", img: "" },
            {
              children: [],
              title: "Payment Settings",
              icon: "",
              img: "",
              route: "/paymentSettings",
            },
          ],
          title: "Settings",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            { children: [], title: "Guests", icon: "", img: "" },
            {
              children: [],
              title: "Corporates",
              icon: "",
              img: "",
              route: "/corporates",
            },
            {
              children: [],
              title: "Discount Rules",
              icon: "",
              img: "",
              route: "/discountRules",
            },
          ],
          title: "Guest",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            { children: [], title: "Unit Status", icon: "", img: "" },
            {
              children: [],
              title: "Housekeeping Staff",
              icon: "",
              img: "",
              route: "/housekeepingstaff",
            },
       
         { children: [], title: "Staff Assignment List", icon: "", img: "",route:'/staffassignlist' },
            { children: [], title: "Staff Assign Room", icon: "", img: "",route:'/staffassignroom' },
            { children: [], title: "Housekeeping Logs", icon: "", img: "",route:'/housekeepinglog' },
            { children: [], title: "Detailed Room Status", icon: "", img: "" },
            { children: [], title: "Assigned Maids", icon: "", img: "" },
          ],
          title: "Housekeeping",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        { children: [], title: "Certificates", icon: "", img: "" },
        { children: [], title: "Enquiry", icon: "", img: "" },
        {
          children: [
            {
              children: [],
              title: "All Laundry Services",
              icon: "",
              img: "",
              route: "/allLaundryServices",
            },
            {
              children: [],
              title: "All Laundry Rates",
              icon: "",
              img: "",
              route: "/allLaundryRates",
            },
            {
              children: [],
              title: "AdHoc Bills",
              icon: "",
              img: "",
              route: "/adHocBills",
            },
            {
              children: [],
              title: "Other Services",
              icon: "",
              img: "",
              route: "/otherServices",
            },
          ],
          title: "Extra Services",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        { children: [], title: "Night Audit", icon: "", img: "",route:'/nightaudit' },
        {
          children: [
            {
              children: [],
              title: "Tax Type",
              icon: "",
              img: "",
              route: "/taxType",
            },
            {
              children: [],
              title: "Tax Category",
              icon: "",
              img: "",
              route: "/taxCategory",
            },
            { children: [], title: "Tax Rules", icon: "", img: "",route:'/taxrule' },
          ],
          title: "Tax Plan Setup",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            {
              children: [],
              title: "All Booking",
              icon: "",
              img: "",
              route: "/allBookings",
            },
            {
              children: [],
              title: "Monthly Reservation Summary",
              icon: "",
              img: "",
              route: "/monthlyReservationSummary",
            },
            {
              children: [],
              title: "Daily Reservation Summary",
              icon: "",
              img: "",
              route: "/dailyReservationSummary",
            },
            {
              children: [],
              title: "Reservation Summary",
              icon: "",
              img: "",
              route: "/reservationSummary",
            },
            {
              children: [],
              title: "Reservation Report",
              icon: "",
              img: "",
              route: "/reservationReport",
            },
            {
              children: [],
              title: "Cancel Report",
              icon: "",
              img: "",
              route: "/cancelReport",
            },
            {
              children: [],
              title: "Occupancy Report",
              icon: "",
              img: "",
              route: "/occupancyReport",
            },
            {
              children: [],
              title: "Travel Agent Report",
              icon: "",
              img: "",
              route: "/travelAgentReport",
            },
            { children: [], title: "Asset Report", icon: "", img: "" },
            {
              children: [],
              title: "Sales Report",
              icon: "",
              img: "",
              route: "/salesReport",
            },
            {
              children: [],
              title: "User Login Report",
              icon: "",
              img: "",
              route: "/userLoginReport",
            },
            {
              children: [],
              title: "Invoice Report",
              icon: "",
              img: "",
              route: "/invoiceReport",
            },
            { children: [], title: "Daily Report", icon: "", img: "" },
          ],
          title: "Reports",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
      ],
    },
    {
      Id:1,
      title: "Restaurant Mgmt",
      icon: "./assets/arrowGreyStroke.svg",
      img: "./assets/circleGreyStroke.svg",
      children: [
        {
          children: [
            { children: [], title: "KOT Placed", icon: "", img: "",route:'/kotplaced' },
            { children: [], title: "KOT Cancel", icon: "", img: "",route:'/kotcancel' },
          ],
          title: "KOT Status",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [],
          title: "Table Master",
          icon: "",
          img: "",
          route: "/tableMaster",
        },
        {
          children: [
            {
              children: [],
              title: "List Waiters",
              icon: "",
              img: "",
              route: "/addWaiter",
            },
          ],
          title: "Waiter Master",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [{ children: [], title: "KOT Report", icon: "", img: "" }],
          title: "KOT Reports",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            { children: [], title: "Sales List", icon: "", img: "",route:'/salelist' },
            { children: [], title: "Cancel Sales", icon: "", img: "",route:'/cancelsales' },
          ],
          title: "Sales",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
      ],
    },
    {
      title: "Inventory",
      icon: "./assets/arrowGreyStroke.svg",
      img: "./assets/cartGreyStroke.svg",
      children: [
        {
          children: [
            {
              children: [],
              title: "Product Master",
              icon: "",
              img: "",
              route: "/productmaster",
            },
            { children: [], title: "Category Master", icon: "", img: "" },
            {
              children: [],
              title: "Warehouse Master",
              icon: "",
              img: "",
              route: "/warehouseMaster",
            },
            {
              children: [],
              title: "Raw Material",
              icon: "",
              img: "",
              route: "",
            },
            {
              children: [],
              title: "UOM Master",
              icon: "",
              img: "",
              route: "/uomMaster",
            },
          ],
          title: "Master",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            { children: [], title: "Stock Summary Report", icon: "", img: "", route:'/stocksummaryreport' },
            {
              children: [],
              title: "Purchase Summaruy Report",
              icon: "",
              img: "",
              route:'/purchasesummaryreport'
            },
            {
              children: [],
              title: "Transfer Summary Report",
              icon: "",
              img: "",
              route:'/transfersummaryreport'
            },
          ],
          title: "Report",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
        {
          children: [
            {
              children: [],
              title: "Asset List",
              icon: "",
              img: "",
              // route: "/addNewAsset",
            },
            {
              children: [],
              title: "Asset Category",
              icon: "",
              img: "",
              route: "/addAssetCategory",
            },
          ],
          title: "Asset Master",
          icon: "./assets/arrowGreyStroke.svg",
          img: "",
        },
      ],
    },
  ];

  export default menuList;